!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 128
  - - clip_range
    - 0.4
  - - ent_coef
    - 0.0
  - - env_wrapper
    - - sb3based.halfcheetah_wrapper.HCWrapper:
          target_vis: true
  - - gae_lambda
    - 0.9
  - - gamma
    - 0.99
  - - learning_rate
    - 3.0e-05
  - - max_grad_norm
    - 0.5
  - - n_envs
    - 16
  - - n_epochs
    - 20
  - - n_steps
    - 512
  - - n_timesteps
    - 3000000.0
  - - normalize
    - gamma: 0.99
      norm_obs_keys:
      - obs
  - - policy
    - MultiInputPolicy
  - - policy_kwargs
    - activation_fn: !!python/name:torch.nn.modules.activation.ReLU ''
      features_extractor_class: !!python/name:sb3based.rnnpolicy.KeyCombinedExtractor ''
      features_extractor_kwargs:
        obs_keys:
        - obs
        - indicator
        - target
      log_std_init: -2
      net_arch:
        pi:
        - 256
        - 256
        vf:
        - 256
        - 256
      ortho_init: false
  - - sde_sample_freq
    - 4
  - - use_sde
    - true
  - - vf_coef
    - 0.5
