!!python/object/apply:collections.OrderedDict
- - - env_wrapper
    - []
  - - learning_rate
    - 2.0633e-05
  - - n_envs
    - 16
  - - n_steps
    - 500
  - - n_timesteps
    - 5000000.0
  - - normalize
    - norm_obs_keys:
      - obs
      - indicator
      - target
  - - policy
    - MultiInputPolicy
  - - policy_kwargs
    - activation_fn: !!python/name:torch.nn.modules.activation.ReLU ''
      features_extractor_class: !!python/name:sb3based.rnnpolicy.KeyCombinedExtractor ''
      features_extractor_kwargs:
        obs_keys:
        - obs
        - target
      log_std_init: -2
      net_arch:
        pi:
        - 256
        - 256
        vf:
        - 256
        - 256
      ortho_init: false
